name: cbs_dft_binder
channels:
  - conda-forge
  - defaults
dependencies:
  - ipykernel=5.3.0
  - matplotlib=3.2.2
  - numpy=1.18.5
  - python=3.8.3
  - qcelemental=0.14.0
  - scipy=1.4.1
  - uncertainties=3.1.4
