name: cbs_dft_binder
channels:
  - psi4/label/dev
  - conda-forge
  - defaults
dependencies:
  - psi4
  - psi4-rt
  - ipykernel
  - matplotlib
  - numpy
  - python
  - qcelemental
  - scipy
  - uncertainties
